### ISSUE TITLE
 SplashProgress has detected a error loading Minecraft.

### ISSUE THREAD

**Issue by HeyZeer0** [AlexIIL/BetterLoadingScreen_1.7#3]
```
// Ouch. That hurt :(

Time: 06/12/16 11:12
Description: Initializing game

SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabeled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
cpw.mods.fml.client.SplashProgress$5: java.lang.IllegalStateException: Splash thread
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:507)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:306)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Splash thread
    at cpw.mods.fml.client.SplashProgress.checkThreadState(SplashProgress.java:438)
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:493)
    ... 10 more
```

This appear in the first time you open the client.

**Comment by Eufranio** [comment]
I got the same crash, happens every time I reinstall the modpack

**Comment by 811Alex** [comment]
It seems to happen when, in the file "config/splash.properties", the property "enable" is set to true, which appears to be the default. It becomes false after the first run. I hope this helps! ^-^
